import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ShowInitialNonce } from "./ShowInitialNonce";
import { headers } from "next/headers";
import Head from "next/head";

// text-lg text-red-500 font-bold
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = headers().get("x-nonce")!;

  return (
    <html lang="en">
      <body className="m-12">
        <div className="flex flex-col gap-3">
          Current nonce: {nonce}
          <ShowInitialNonce nonce={nonce} />
          {children}
        </div>
      </body>
    </html>
  );
}
